city_name: London
pois_gdf_path: test/data/pois_test.gpkg
iso_polygons_gdf_path: data/london/isochrones/walk_isochrones.gpkg
drive_iso_gdf_path: test/data/drive_isos_test.gpkg
crs: 32718
matching_column: stop_id
output_path: results/
hexagon_gdf_path: data/hexagons_7.geojson
date: "17:00:00"
minute_threshold: 30

