city_name: London
pois_gdf_path: data/test_pois.geojson
iso_polygons_gdf_path: data/test_walk_iso_for_hex.geojson
drive_iso_gdf_path: data/test_drive_iso_for_hex.geojson
crs: 4326
matching_column: hex_id
output_path: results/
hexagon_gdf_path: data/london/hexagons_9.geojson
hexagon_centroid_gdf_path: data/test_hex_centroids.geojson
selected_isochrones_path: data/london/isochrones/selected_isochrones.geojson
date: "17:00:00"
minute_threshold: 30
rush_hour_speed: 14
bus_speed: 60
walk_isochrones_from_hex_gdf_path: data/test_walk_iso_for_hex.geojson
mode: normal

