city_name: Lima
pois_gdf_path: ../data/lima/pois_lima.geojson
iso_polygons_gdf_path: ../data/lima/isos_walk_lima.gpkg
drive_iso_gdf_path: ../data/lima/drive_isos_hex_lima.gpkg
crs: 4326
matching_column: uuid
output_path: ../results/
hexagon_gdf_path: ../data/lima/hexagons_lima.geojson
hexagon_centroid_gdf_path: ../data/lima/hex_centroids_lima.gpkg
walk_isochrones_from_hex_gdf_path: ../data/test_walk_iso_for_hex.geojson
computed_iso_polygons_gdf_path: ../data/lima/calc_isos_lima.geojson
